'use client';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect } from 'react';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const meta: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const pathname = usePathname();

  useEffect(() => {
  const accessToken = localStorage.getItem('accessToken');
  console.log('Access Token:', accessToken, 'Pathname:', pathname);
  if (!accessToken && pathname !== '/login') {
    router.push('/login');
  }
  if (accessToken && pathname === '/login') {
    router.push('/Dashboard');
  }
}, [pathname, router]);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <Navbar  />
       
        <main>{children}</main>
      </body>
    </html>
  );
}